version: '3'
services:
  postgres:
    image: 'postgres:10.23-alpine3.16'
  redis:
    image: 'redis:4.0.14-alpine'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
